# Generated by Django 2.1.7 on 2019-03-25 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
        ('composition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='总分')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.CompetitionModel')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composition.CompositionModel')),
            ],
        ),
    ]
