# Generated by Django 2.1.7 on 2019-03-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_grademodel_judger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grademodel',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='grademodel',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='grademodel',
            name='judger',
        ),
        migrations.DeleteModel(
            name='GradeModel',
        ),
    ]
