# Generated by Django 2.1.7 on 2019-03-26 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('composition', '0002_auto_20190326_1633'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grade', '0003_auto_20190326_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composition.CompositionModel')),
                ('judger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
            },
        ),
    ]
