# Generated by Django 2.1.7 on 2019-04-05 18:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('composition', '0003_auto_20190402_1556'),
        ('grade', '0004_grademodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grademodel',
            unique_together={('judger', 'composition')},
        ),
    ]
