# Generated by Django 2.1.7 on 2019-03-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compositionmodel',
            options={'verbose_name': '作品', 'verbose_name_plural': '作品'},
        ),
    ]
