# Generated by Django 2.1.7 on 2019-04-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_auto_20190326_1633'),
        ('composition', '0002_auto_20190326_1633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compositionmodel',
            unique_together={('number', 'competition')},
        ),
    ]
