# Generated by Django 2.1.7 on 2019-03-25 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_competitionmodel_judger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionmodel',
            name='judger',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
