# Generated by Django 2.2 on 2019-04-21 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_competitionmodel_judger'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
    ]
