# Generated by Django 2.1.7 on 2019-03-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20190325_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionmodel',
            options={'verbose_name': '比赛', 'verbose_name_plural': '比赛'},
        ),
    ]
